### ISSUE TITLE
run error 

### ISSUE THREAD

**Issue by yebuxiu123** [Jarvis73/FPTrans#2] opened 2022-12-03 14:54 UTC
I follow your steps to precompute cross-entropy weights,  when I run: cuda 0 python tools.py precompute_loss_weights with dataset=PASCAL dry_run=True 
This error occurred: sacred.utils.ConfigAddedError: Added new config entry that is not used anywhere
Conflicting configuration values:
  dry_run=True
And then I run： cuda 0 python tools.py precompute_loss_weights with dataset=PASCAL
This error occurred: ValueError: Can not open file /home/gc/deskbook/FPTrans-main/data/VOCdevkit/VOC2012/SegmentationClassAug/2008_000008.png.
Actually，the image 2008_000008.png does not exist in the VOC dataset， I don't know what the problem is and  hope you can give me an answer.

**Comment by Jarvis73** [comment] 2022-12-04 08:01
Hi, @yebuxiu123 
1. The `dry_run` bug has been fixed. 
2. I forgot to provide a link to download the `SegmentationClassAug` dataset, and now I have updated the [data/README.md](https://github.com/Jarvis73/FPTrans/tree/main/data).

**Comment by yebuxiu123** [comment] 2022-12-05 03:39
Thank you for your help, the problem above has been solved， but new problems have arisen，when I run the test mode ： cuda 0 python run.py test with configs/pascal_vit.yml exp_id=1 split=0
This error occurred:
Traceback (most recent calls WITHOUT Sacred internals):
  File "/home/gc/deskbook/FPTrans-main/run.py", line 121, in test
    loss, mean_iou, binary_iou, _, _ = tester.start_eval_loop(data_loader, num_classes)
  File "/home/gc/anaconda3/envs/fptrans/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "/home/gc/deskbook/FPTrans-main/core/base_trainer.py", line 123, in start_eval_loop
    data_loader.dataset.sample_tasks()
  File "/home/gc/deskbook/FPTrans-main/data_kits/voc_coco.py", line 198, in sample_tasks
    rounds = (total_length + self.length_data_list - 1) // self.length_data_list
ZeroDivisionError: integer division or modulo by zero

This time I'm not sure if it's my environment or your code that's the problem，I hope I'm not disturbing you.

**Comment by Jarvis73** [comment] 2022-12-06 03:33
It is caused by the default cached val list in `./lists/pascal/val_0.pkl`. 
In your previous run, the dataset has not been fully prepared (e.g., missing SegmentationClassAug), and the empty val list is still cached in `./lists/pascal/val_0.pkl`. In the new run, the procedure will load the cached empty val list and result in `self.length_data_list` being zero. 

You can just remove the old `./lists/pascal/val_0.pkl`. Then everything should be ok. 
Or you can download the latest version of the code, where I have fixed this bug. The procedure will regenerate `val_0.pkl` if it is empty.

**Comment by Jarvis73** [comment] 2022-12-11 12:43
I will close this issue. Feel free to reopen it if there are any other questions.

**Closed as completed by Jarvis73** 2022-12-11 12:43 UTC
